version: '3.8'

services:
  web:
    build: ./
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - ./.env.prod
    environment:
      - POSTGRES_USER=prod_django
      - POSTGRES_PASSWORD=prod_django
      - POSTGRES_DB=prod_django
volumes:
  postgres_data:
